### PR TITLE
fix: handle AccessDenied in report for macOS

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [x] At least some minimal testing

https://gist.github.com/BasilHorowt/52883871039c748d76cb8dafdf00f0d2
<details> <summary>full traceback</summary>

```python-traceback
Traceback (most recent call last):
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 365, in catch_zombie
    yield
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 406, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chia/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/plotman/plotman.py", line 171, in main
    interactive.run_interactive()
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/plotman/interactive.py", line 353, in run_interactive
    curses.wrapper(curses_main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/plotman/interactive.py", line 271, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_h, 
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/plotman/reporting.py", line 107, in status_report
    plot_util.human_format(j.get_mem_usage(), 1),
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/plotman/job.py", line 278, in get_mem_usage
    return self.proc.memory_info().vms  # Total, inc swapped
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/__init__.py", line 1054, in memory_info
    return self._proc.memory_info()
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 475, in memory_info
    rawtuple = self._get_pidtaskinfo()
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 406, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chia/chia-blockchain/venv/lib/python3.9/site-packages/psutil/_psosx.py", line 378, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil.AccessDenied: psutil.AccessDenied (pid=14694)
```

</details>

### CODE REVIEW

**Comment by altendky** [comment]
@BasilHorowt, let me know if you can try this out.  I understand we can't force the issue to prove it has been fixed, but it would be nice to get at least a little test time on this in the environment where the failure occurred.

**Comment by alibosworth** [comment]
I can definitely switch to this branch and leave it running, however, do you have a sense of what the triggering situation is? Is it about a plot finishing?

**Comment by BasilHorowt** [comment]
I can definitely switch to this branch and leave it running, however, do you have a sense of what the triggering situation is? Is it about a plot finishing?

**Comment by altendky** [comment]
Sorry.  Yes, your analysis made perfect sense.  There were sort of two related issues.  First that by the time the identified process is analyzed, it may be gone.  Or may be a zombie and there are different permissions for that on macOS maybe?  I can't say I dug into that in great detail since it fits with other macOS differences we've dealt with.  This is addressed by adding the `psutil.AccessDenied` exception so it is caught as well.  Second, that we didn't collect all the process info at one time and rather grabbed it piece by piece which meant that there were several opportunities to fail even after we already had gotten some info about the process.  That's what the `with j.proc.one_shot():` is for.

**Comment by alibosworth** [comment]
@altendky I didn't have a chance to switch to this until now, and I get this on trying to `plotman interactive`!

`AttributeError: 'Process' object has no attribute 'one_shot'`

**Comment by BasilHorowt** [comment]
@altendky I didn't have a chance to switch to this until now, and I get this on trying to plotman interactive!

AttributeError: 'Process' object has no attribute 'one_shot'

**Comment by altendky** [comment]
It would seem that I did something silly... Thanks for the feedback. The erroneous underscore has been removed.

**Comment by BasilHorowt** [comment]
Ah cool, works now :) will leave it running on my main plotting machine.

**Review by BasilHorowt — APPROVED** [review]
Take this with a grain of salt given I am not at all familiar with Python or process stuff, but this is working well for me and it looks good based on your description of how the changes work.

**Pull request merged**
