### PR TITLE
Adds a link to the Archiving wiki in the default config in order to help new users.

### PR DESCRIPTION
**Pull request by mjsr**
New user here. I had trouble understanding Archiving. Looking at the number of open issues, it looks like I'm not the same.

Found the pretty good [Archiving wiki page](https://github.com/ericaltendorf/plotman/wiki/Archiving) and [updated it](https://github.com/ericaltendorf/plotman/issues/227).

I believe that adding a link to the Archiving wiki will allow new users like myself and reduce the number of open issues.

### CODE REVIEW

**Review by mist0706 — APPROVED** [review]
Looks good!

**Comment by mjsr** [comment]
@mist0706 not sure what's pending (not very familiar with GitHub pull requests to be honest). It's currently saying there's 1 workflow awaiting approval. Are you able to do that or should this be someone else?

**Comment by mist0706** [comment]
First time contributions require a maintainer approval

**Comment by mjsr** [comment]
Right, I can see that there. I thought you were a maintainer that could do it :)

**Review by ericaltendorf — APPROVED** [review]

**Comment by ericaltendorf** [comment]
Thanks for the contribution!  In the future, please try to submit changes based against branch `development`.  I know this wasn't documented before; I just added https://github.com/ericaltendorf/plotman/wiki/Contributing .  Thanks!

**Pull request merged**
