### PR TITLE
Fixup tmp cleanup

### PR DESCRIPTION
**Pull request by altendky**
https://github.com/ericaltendorf/plotman/discussions/912

### CODE REVIEW

**Comment by altendky** [comment]
I'm getting file names such as `plot-k32-2021-08-28-15-05-0b9e4436b8279739d582e3213277040bc9bea4c40bc72aff552fcda56f775d46.p1.t1.sort_bucket_9.tmp` from madMAx anyways.  The existing pattern doesn't match this.

**Comment by altendky** [comment]
And `plot-k25-2021-08-28-15-19-2762fbdc8cc76b1e90d646db6e199522fed8ef5db8602b253e2b1fd1854a7263.plot.p1.t1.sort_bucket_079.tmp` from chiapos.

**Comment by altendky** [comment]
err, need a changelog entry

**Review by ericaltendorf — APPROVED** [review]
Looks good.  FWIW I'm on board with creating a new directory for each plot job and using that for isolation, then we could use full wildcard.

**Comment by altendky** [comment]
Yep, that's somewhere on the list...

**Pull request merged**
