### PR TITLE
Use tmp as dst when it is also a dst

### PR DESCRIPTION
**Pull request by djdjukic**
Modified manager.py to detect when a selected tmpdir is also configured as a dst, and, in that case, use it as the dstdir in order to avoid unneccessary copying. Useful for plotting directly to HDD.

### CODE REVIEW

**Comment by syadnom** [comment]
upvote!

**Comment by altendky** [comment]
So for some tmps you want separate dsts and for other tmps you want dst-on-tmp?

**Comment by djdjukic** [comment]
@altendky Yes. I want to plot in two ways:

1. conventional SSD-to-HDD plotting - SSD tmp, HDD dst
2. whole plotting process entirely on HDD - HDD tmp, same HDD dst

What we have now is random tmp, random (HDD) dst.

A good addition to this PR would be a way to set tmpdir_max_jobs individually per tmp, to allow us to set 1 max plot for HDD tmps and 2 or more for SSD tmps.

**Comment by altendky** [comment]
You already have the tmp overrides to cover the extra bit you mentioned of per-tmp plot limits.  I'll think about this but my general plan is to long term work towards being able to specify multiple workflows.  In your case you would have two.

**Comment by djdjukic** [comment]
Multiple workflows - that sounds even better. Though I think this commit would still make a good default for mixed setups. Thanks for the tip about tmp overrides, I glossed over that setting, it does just what I want.

**Comment by altendky** [comment]
@djdjukic, I took the liberty of doing a catch up merge for you.  Could you try it out and make sure I got it right?  If so, we can go ahead and merge this.  Thanks for your contribution and my apologies for being so slow about this.

**Comment by djdjukic** [comment]
@altendky I have now tested the updated branch, and this feature indeed works as it should. Thank you!

**Pull request merged**
