### PR TITLE
preliminary bladebit2 disk support

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [ ] Deleting tmp files, needs bb2d to name them accordingly, may involve handling a subdirectory.

### CODE REVIEW

**Comment by erans** [comment]
@altendky anything I can do to help getting this merged?

**Comment by altendky** [comment]
Have you run this branch?  Is it working alright for you?  I guess we can leave the temp file cleanup just not implemented at this point.

**Comment by altendky** [comment]
Kicking CI

**Comment by erans** [comment]
Not yet, but I'm considering to try and test plotman + bladebit + soon to be plot compression. As far as I understand, that's not available yet in the regular madmax plotter and should be available with bladebit.

**Comment by altendky** [comment]
Plot compression hasn't gotten to beta yet from Chia.  I'll have to add some options for the compression control as well.  Anyways, I'll try to get this merged to `development` and you can do some testing if you have a chance and I'll plan to get Bladebit CUDA and compression support when they are out anyways.  Feel free to ping with an issue when they are released for beta if I don't make up a PR first.

**Comment by erans** [comment]
I know its not ready yet, but we should probably have the regular bladebit disk working in preparation just in case :)

**Pull request merged**
